### ISSUE TITLE
Default boilerplate theme

### ISSUE THREAD

**Issue by thomasdavis** [kelyvin/jsonresume-theme-caffeine#1]
Hey Kelvin, just stumbled upon the work you have been doing here.

It would make absolute sense for us to have a more robust setup like the one you have built here.

How far off do you think we would be from doing so?

I am imagining setting up a dedicated "Theme Development" page.

**Comment by kelyvin** [comment]
Hi Thomas, thanks for the message. First off, I'm a fan of jsonresume project and you've done excellent work there. 

I had originally set up this repo because I saw some gaps in my productivity with the original system. When I was in the process of building out my own theme, I wanted to make it easier for me to make iterative changes and visually see the impact very quickly, so I spun this up in several hours on a Sunday (all the important commits were done on May 22nd) 

As a result, I don't think it'll take too much effort to update your current setup. This project simply wraps around your current resume-cli. So with some minor tweaks to that project, you can have something very similar set up. You can also make it easier for your users to get started with theme development by setting up a simple project structure and allowing a scaffolding engine like Yeoman to enable your users to "pick their own flavor". That's essentially what's going on in my project and how I set this up; I scaffolded out a development environment that I created a while back, and simply had it wrap around the resume-cli.

Let me know what you think or if there's anything you'd like me to help with. Thanks!

**Comment by thomasdavis** [comment]
I believe this theme is crashing the theme server, trying to figure out why.

**Comment by kelyvin** [comment]
@thomasdavis Sorry about that, I published the theme for the first time and there was a small error in my npmignore that omitted a file that broke the package. It should be fixed now

**Comment by thomasdavis** [comment]
Not your fault at all, the theme server should be able to handle broken themes without crashing.

http://registry.jsonresume.org/thomasdavis?theme=caffeine

Seems to be working now though

**Comment by kelyvin** [comment]
Awesome glad to hear it! Let me know if there's anything I can help with.
